2025-03-05 20:18:13,091 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BINANCE_FUTURES/btcusdt/2025-03-04-00.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:14,943 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BINANCE_FUTURES/btcusdt/2025-03-04-01.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:16,205 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BINANCE_FUTURES/btcusdt/2025-03-04-02.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:16,726 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BINANCE_FUTURES/btcusdt/2025-03-04-03.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:17,145 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BINANCE_FUTURES/btcusdt/2025-03-04-04.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:17,705 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BINANCE_FUTURES/btcusdt/2025-03-04-05.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:18,005 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BINANCE_FUTURES/btcusdt/2025-03-04-06.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:18,366 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BINANCE_FUTURES/btcusdt/2025-03-04-07.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:18,785 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BINANCE_FUTURES/btcusdt/2025-03-04-08.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:19,090 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BINANCE_FUTURES/btcusdt/2025-03-04-09.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:19,384 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BINANCE_FUTURES/btcusdt/2025-03-04-10.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:19,707 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BINANCE_FUTURES/btcusdt/2025-03-04-11.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:20,095 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BINANCE_FUTURES/btcusdt/2025-03-04-12.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:20,953 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BINANCE_FUTURES/btcusdt/2025-03-04-13.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:22,908 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BINANCE_FUTURES/btcusdt/2025-03-04-14.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:24,617 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BINANCE_FUTURES/btcusdt/2025-03-04-15.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:25,298 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BINANCE_FUTURES/btcusdt/2025-03-04-16.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:26,373 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BINANCE_FUTURES/btcusdt/2025-03-04-17.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:27,251 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BINANCE_FUTURES/btcusdt/2025-03-04-18.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:28,356 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BINANCE_FUTURES/btcusdt/2025-03-04-19.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:29,224 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BINANCE_FUTURES/btcusdt/2025-03-04-20.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:30,072 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BINANCE_FUTURES/btcusdt/2025-03-04-21.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:30,319 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BINANCE_FUTURES/btcusdt/2025-03-04-22.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:30,567 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BINANCE_FUTURES/btcusdt/2025-03-04-23.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:31,013 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BINANCE_FUTURES/btcusdt/2025-03-05-00.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:31,460 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BINANCE_FUTURES/btcusdt/2025-03-05-01.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:31,944 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BINANCE_FUTURES/btcusdt/2025-03-05-02.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:32,316 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BINANCE_FUTURES/btcusdt/2025-03-05-03.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:32,635 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BINANCE_FUTURES/btcusdt/2025-03-05-04.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:32,797 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BINANCE_FUTURES/btcusdt/2025-03-05-05.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:32,970 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BINANCE_FUTURES/btcusdt/2025-03-05-06.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:33,167 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BINANCE_FUTURES/btcusdt/2025-03-05-07.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:33,398 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BINANCE_FUTURES/btcusdt/2025-03-05-08.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:33,842 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BINANCE_FUTURES/btcusdt/2025-03-05-09.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:34,682 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BINANCE_FUTURES/btcusdt/2025-03-05-10.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:35,134 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BINANCE_FUTURES/btcusdt/2025-03-05-11.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:35,812 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BINANCE_FUTURES/btcusdt/2025-03-05-12.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:36,562 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BINANCE_FUTURES/btcusdt/2025-03-05-13.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:37,687 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BINANCE_FUTURES/btcusdt/2025-03-05-14.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:38,784 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BINANCE_FUTURES/btcusdt/2025-03-05-15.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:39,670 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BINANCE_FUTURES/btcusdt/2025-03-05-16.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:39,772 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BINANCE_FUTURES/btcusd_perp/2025-03-04-00.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:39,998 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BINANCE_FUTURES/btcusd_perp/2025-03-04-01.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:40,140 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BINANCE_FUTURES/btcusd_perp/2025-03-04-02.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:40,203 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BINANCE_FUTURES/btcusd_perp/2025-03-04-03.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:40,254 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BINANCE_FUTURES/btcusd_perp/2025-03-04-04.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:40,321 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BINANCE_FUTURES/btcusd_perp/2025-03-04-05.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:40,357 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BINANCE_FUTURES/btcusd_perp/2025-03-04-06.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:40,398 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BINANCE_FUTURES/btcusd_perp/2025-03-04-07.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:40,445 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BINANCE_FUTURES/btcusd_perp/2025-03-04-08.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:40,478 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BINANCE_FUTURES/btcusd_perp/2025-03-04-09.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:40,513 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BINANCE_FUTURES/btcusd_perp/2025-03-04-10.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:40,547 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BINANCE_FUTURES/btcusd_perp/2025-03-04-11.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:40,589 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BINANCE_FUTURES/btcusd_perp/2025-03-04-12.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:40,684 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BINANCE_FUTURES/btcusd_perp/2025-03-04-13.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:40,940 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BINANCE_FUTURES/btcusd_perp/2025-03-04-14.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:41,158 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BINANCE_FUTURES/btcusd_perp/2025-03-04-15.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:41,276 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BINANCE_FUTURES/btcusd_perp/2025-03-04-16.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:41,406 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BINANCE_FUTURES/btcusd_perp/2025-03-04-17.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:41,503 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BINANCE_FUTURES/btcusd_perp/2025-03-04-18.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:41,626 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BINANCE_FUTURES/btcusd_perp/2025-03-04-19.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:41,739 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BINANCE_FUTURES/btcusd_perp/2025-03-04-20.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:41,884 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BINANCE_FUTURES/btcusd_perp/2025-03-04-21.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:41,920 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BINANCE_FUTURES/btcusd_perp/2025-03-04-22.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:41,950 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BINANCE_FUTURES/btcusd_perp/2025-03-04-23.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:42,010 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BINANCE_FUTURES/btcusd_perp/2025-03-05-00.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:42,065 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BINANCE_FUTURES/btcusd_perp/2025-03-05-01.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:42,147 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BINANCE_FUTURES/btcusd_perp/2025-03-05-02.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:42,222 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BINANCE_FUTURES/btcusd_perp/2025-03-05-03.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:42,271 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BINANCE_FUTURES/btcusd_perp/2025-03-05-04.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:42,302 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BINANCE_FUTURES/btcusd_perp/2025-03-05-05.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:42,325 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BINANCE_FUTURES/btcusd_perp/2025-03-05-06.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:42,359 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BINANCE_FUTURES/btcusd_perp/2025-03-05-07.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:42,392 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BINANCE_FUTURES/btcusd_perp/2025-03-05-08.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:42,482 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BINANCE_FUTURES/btcusd_perp/2025-03-05-09.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:42,610 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BINANCE_FUTURES/btcusd_perp/2025-03-05-10.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:42,694 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BINANCE_FUTURES/btcusd_perp/2025-03-05-11.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:42,810 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BINANCE_FUTURES/btcusd_perp/2025-03-05-12.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:42,915 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BINANCE_FUTURES/btcusd_perp/2025-03-05-13.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:43,055 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BINANCE_FUTURES/btcusd_perp/2025-03-05-14.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:43,194 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BINANCE_FUTURES/btcusd_perp/2025-03-05-15.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:43,299 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BINANCE_FUTURES/btcusd_perp/2025-03-05-16.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:43,685 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BYBIT/BTCUSDT/2025-03-04-00.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:45,061 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BYBIT/BTCUSDT/2025-03-04-01.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:45,779 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BYBIT/BTCUSDT/2025-03-04-02.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:46,069 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BYBIT/BTCUSDT/2025-03-04-03.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:46,315 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BYBIT/BTCUSDT/2025-03-04-04.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:46,676 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BYBIT/BTCUSDT/2025-03-04-05.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:46,831 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BYBIT/BTCUSDT/2025-03-04-06.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:47,021 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BYBIT/BTCUSDT/2025-03-04-07.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:47,231 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BYBIT/BTCUSDT/2025-03-04-08.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:47,378 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BYBIT/BTCUSDT/2025-03-04-09.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:47,524 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BYBIT/BTCUSDT/2025-03-04-10.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:47,673 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BYBIT/BTCUSDT/2025-03-04-11.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:47,858 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BYBIT/BTCUSDT/2025-03-04-12.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:48,362 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BYBIT/BTCUSDT/2025-03-04-13.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:49,870 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BYBIT/BTCUSDT/2025-03-04-14.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:50,922 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BYBIT/BTCUSDT/2025-03-04-15.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:51,510 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BYBIT/BTCUSDT/2025-03-04-16.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:52,076 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BYBIT/BTCUSDT/2025-03-04-17.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:52,580 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BYBIT/BTCUSDT/2025-03-04-18.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:53,249 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BYBIT/BTCUSDT/2025-03-04-19.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:53,785 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BYBIT/BTCUSDT/2025-03-04-20.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:54,293 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BYBIT/BTCUSDT/2025-03-04-21.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:54,427 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BYBIT/BTCUSDT/2025-03-04-22.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:54,550 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BYBIT/BTCUSDT/2025-03-04-23.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:54,757 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BYBIT/BTCUSDT/2025-03-05-00.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:54,939 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BYBIT/BTCUSDT/2025-03-05-01.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:55,115 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BYBIT/BTCUSDT/2025-03-05-02.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:55,265 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BYBIT/BTCUSDT/2025-03-05-03.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:55,391 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BYBIT/BTCUSDT/2025-03-05-04.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:55,466 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BYBIT/BTCUSDT/2025-03-05-05.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:55,552 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BYBIT/BTCUSDT/2025-03-05-06.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:55,641 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BYBIT/BTCUSDT/2025-03-05-07.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:55,743 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BYBIT/BTCUSDT/2025-03-05-08.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:55,976 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BYBIT/BTCUSDT/2025-03-05-09.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:56,479 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BYBIT/BTCUSDT/2025-03-05-10.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:56,686 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BYBIT/BTCUSDT/2025-03-05-11.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:57,057 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BYBIT/BTCUSDT/2025-03-05-12.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:57,451 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BYBIT/BTCUSDT/2025-03-05-13.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:58,146 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BYBIT/BTCUSDT/2025-03-05-14.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:58,769 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BYBIT/BTCUSDT/2025-03-05-15.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:59,173 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BYBIT/BTCUSDT/2025-03-05-16.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:59,222 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BITFINEX/BTCUSD/2025-03-04-00.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:59,234 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BITFINEX/BTCUSD/2025-03-04-01.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:59,246 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BITFINEX/BTCUSD/2025-03-04-02.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:59,257 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BITFINEX/BTCUSD/2025-03-04-03.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:59,266 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BITFINEX/BTCUSD/2025-03-04-04.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:59,273 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BITFINEX/BTCUSD/2025-03-04-05.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:59,279 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BITFINEX/BTCUSD/2025-03-04-06.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:59,286 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BITFINEX/BTCUSD/2025-03-04-07.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:59,295 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BITFINEX/BTCUSD/2025-03-04-08.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:59,302 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BITFINEX/BTCUSD/2025-03-04-09.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:59,309 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BITFINEX/BTCUSD/2025-03-04-10.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:59,316 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BITFINEX/BTCUSD/2025-03-04-11.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:59,323 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BITFINEX/BTCUSD/2025-03-04-12.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:59,332 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BITFINEX/BTCUSD/2025-03-04-13.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:59,344 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BITFINEX/BTCUSD/2025-03-04-14.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:59,356 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BITFINEX/BTCUSD/2025-03-04-15.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:59,365 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BITFINEX/BTCUSD/2025-03-04-16.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:59,375 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BITFINEX/BTCUSD/2025-03-04-17.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:59,383 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BITFINEX/BTCUSD/2025-03-04-18.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:59,393 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BITFINEX/BTCUSD/2025-03-04-19.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:59,402 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BITFINEX/BTCUSD/2025-03-04-20.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:59,410 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BITFINEX/BTCUSD/2025-03-04-21.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:59,419 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BITFINEX/BTCUSD/2025-03-04-22.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:59,425 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BITFINEX/BTCUSD/2025-03-04-23.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:59,431 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BITFINEX/BTCUSD/2025-03-05-00.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:59,437 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BITFINEX/BTCUSD/2025-03-05-01.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:59,443 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BITFINEX/BTCUSD/2025-03-05-02.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:59,448 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BITFINEX/BTCUSD/2025-03-05-03.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:59,453 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BITFINEX/BTCUSD/2025-03-05-04.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:59,457 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BITFINEX/BTCUSD/2025-03-05-05.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:59,463 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BITFINEX/BTCUSD/2025-03-05-06.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:59,467 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BITFINEX/BTCUSD/2025-03-05-07.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:59,472 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BITFINEX/BTCUSD/2025-03-05-08.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:59,479 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BITFINEX/BTCUSD/2025-03-05-09.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:59,488 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BITFINEX/BTCUSD/2025-03-05-10.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:59,493 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BITFINEX/BTCUSD/2025-03-05-11.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:59,502 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BITFINEX/BTCUSD/2025-03-05-12.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:59,510 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BITFINEX/BTCUSD/2025-03-05-13.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:59,519 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BITFINEX/BTCUSD/2025-03-05-14.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:59,528 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BITFINEX/BTCUSD/2025-03-05-15.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:59,537 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BITFINEX/BTCUSD/2025-03-05-16.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:59,729 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/OKEX/BTC-USDT-SWAP/2025-03-04-00.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:18:59,731 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/OKEX/BTC-USDT-SWAP/2025-03-04-01.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:00,146 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/OKEX/BTC-USDT-SWAP/2025-03-04-02.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:00,321 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/OKEX/BTC-USDT-SWAP/2025-03-04-03.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:00,478 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/OKEX/BTC-USDT-SWAP/2025-03-04-04.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:00,694 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/OKEX/BTC-USDT-SWAP/2025-03-04-05.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:00,820 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/OKEX/BTC-USDT-SWAP/2025-03-04-06.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:00,956 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/OKEX/BTC-USDT-SWAP/2025-03-04-07.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:01,121 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/OKEX/BTC-USDT-SWAP/2025-03-04-08.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:01,241 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/OKEX/BTC-USDT-SWAP/2025-03-04-09.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:01,358 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/OKEX/BTC-USDT-SWAP/2025-03-04-10.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:01,474 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/OKEX/BTC-USDT-SWAP/2025-03-04-11.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:01,611 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/OKEX/BTC-USDT-SWAP/2025-03-04-12.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:01,971 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/OKEX/BTC-USDT-SWAP/2025-03-04-13.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:01,974 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/OKEX/BTC-USDT-SWAP/2025-03-04-14.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:01,976 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/OKEX/BTC-USDT-SWAP/2025-03-04-15.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:01,979 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/OKEX/BTC-USDT-SWAP/2025-03-04-16.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:01,982 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/OKEX/BTC-USDT-SWAP/2025-03-04-17.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:01,985 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/OKEX/BTC-USDT-SWAP/2025-03-04-18.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:01,988 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/OKEX/BTC-USDT-SWAP/2025-03-04-19.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:02,273 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/OKEX/BTC-USDT-SWAP/2025-03-04-20.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:02,593 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/OKEX/BTC-USDT-SWAP/2025-03-04-21.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:02,681 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/OKEX/BTC-USDT-SWAP/2025-03-04-22.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:02,764 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/OKEX/BTC-USDT-SWAP/2025-03-04-23.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:02,921 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/OKEX/BTC-USDT-SWAP/2025-03-05-00.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:03,065 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/OKEX/BTC-USDT-SWAP/2025-03-05-01.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:03,207 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/OKEX/BTC-USDT-SWAP/2025-03-05-02.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:03,329 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/OKEX/BTC-USDT-SWAP/2025-03-05-03.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:03,442 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/OKEX/BTC-USDT-SWAP/2025-03-05-04.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:03,507 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/OKEX/BTC-USDT-SWAP/2025-03-05-05.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:03,572 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/OKEX/BTC-USDT-SWAP/2025-03-05-06.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:03,649 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/OKEX/BTC-USDT-SWAP/2025-03-05-07.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:03,728 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/OKEX/BTC-USDT-SWAP/2025-03-05-08.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:03,912 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/OKEX/BTC-USDT-SWAP/2025-03-05-09.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:04,292 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/OKEX/BTC-USDT-SWAP/2025-03-05-10.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:04,460 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/OKEX/BTC-USDT-SWAP/2025-03-05-11.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:04,748 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/OKEX/BTC-USDT-SWAP/2025-03-05-12.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:05,056 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/OKEX/BTC-USDT-SWAP/2025-03-05-13.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:05,505 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/OKEX/BTC-USDT-SWAP/2025-03-05-14.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:05,945 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/OKEX/BTC-USDT-SWAP/2025-03-05-15.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:06,266 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/OKEX/BTC-USDT-SWAP/2025-03-05-16.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:06,308 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/OKEX/BTC-USD-SWAP/2025-03-04-00.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:06,311 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/OKEX/BTC-USD-SWAP/2025-03-04-01.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:06,398 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/OKEX/BTC-USD-SWAP/2025-03-04-02.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:06,429 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/OKEX/BTC-USD-SWAP/2025-03-04-03.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:06,454 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/OKEX/BTC-USD-SWAP/2025-03-04-04.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:06,485 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/OKEX/BTC-USD-SWAP/2025-03-04-05.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:06,503 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/OKEX/BTC-USD-SWAP/2025-03-04-06.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:06,531 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/OKEX/BTC-USD-SWAP/2025-03-04-07.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:06,561 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/OKEX/BTC-USD-SWAP/2025-03-04-08.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:06,580 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/OKEX/BTC-USD-SWAP/2025-03-04-09.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:06,598 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/OKEX/BTC-USD-SWAP/2025-03-04-10.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:06,620 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/OKEX/BTC-USD-SWAP/2025-03-04-11.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:06,645 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/OKEX/BTC-USD-SWAP/2025-03-04-12.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:06,693 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/OKEX/BTC-USD-SWAP/2025-03-04-13.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:06,696 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/OKEX/BTC-USD-SWAP/2025-03-04-14.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:06,810 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/OKEX/BTC-USD-SWAP/2025-03-04-15.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:06,813 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/OKEX/BTC-USD-SWAP/2025-03-04-16.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:06,815 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/OKEX/BTC-USD-SWAP/2025-03-04-17.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:06,818 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/OKEX/BTC-USD-SWAP/2025-03-04-18.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:06,884 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/OKEX/BTC-USD-SWAP/2025-03-04-19.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:06,925 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/OKEX/BTC-USD-SWAP/2025-03-04-20.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:06,970 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/OKEX/BTC-USD-SWAP/2025-03-04-21.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:06,985 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/OKEX/BTC-USD-SWAP/2025-03-04-22.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:07,001 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/OKEX/BTC-USD-SWAP/2025-03-04-23.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:07,038 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/OKEX/BTC-USD-SWAP/2025-03-05-00.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:07,063 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/OKEX/BTC-USD-SWAP/2025-03-05-01.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:07,089 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/OKEX/BTC-USD-SWAP/2025-03-05-02.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:07,116 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/OKEX/BTC-USD-SWAP/2025-03-05-03.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:07,136 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/OKEX/BTC-USD-SWAP/2025-03-05-04.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:07,151 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/OKEX/BTC-USD-SWAP/2025-03-05-05.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:07,163 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/OKEX/BTC-USD-SWAP/2025-03-05-06.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:07,188 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/OKEX/BTC-USD-SWAP/2025-03-05-07.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:07,217 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/OKEX/BTC-USD-SWAP/2025-03-05-08.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:07,239 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/OKEX/BTC-USD-SWAP/2025-03-05-09.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:07,292 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/OKEX/BTC-USD-SWAP/2025-03-05-10.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:07,318 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/OKEX/BTC-USD-SWAP/2025-03-05-11.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:07,358 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/OKEX/BTC-USD-SWAP/2025-03-05-12.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:07,406 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/OKEX/BTC-USD-SWAP/2025-03-05-13.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:07,472 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/OKEX/BTC-USD-SWAP/2025-03-05-14.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:07,542 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/OKEX/BTC-USD-SWAP/2025-03-05-15.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:07,589 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/OKEX/BTC-USD-SWAP/2025-03-05-16.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:08,442 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BINANCE/btcusdt/2025-03-04-00.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:10,282 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BINANCE/btcusdt/2025-03-04-01.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:11,760 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BINANCE/btcusdt/2025-03-04-02.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:12,487 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BINANCE/btcusdt/2025-03-04-03.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:13,199 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BINANCE/btcusdt/2025-03-04-04.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:14,048 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BINANCE/btcusdt/2025-03-04-05.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:14,485 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BINANCE/btcusdt/2025-03-04-06.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:15,027 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BINANCE/btcusdt/2025-03-04-07.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:15,656 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BINANCE/btcusdt/2025-03-04-08.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:16,156 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BINANCE/btcusdt/2025-03-04-09.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:16,629 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BINANCE/btcusdt/2025-03-04-10.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:17,145 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BINANCE/btcusdt/2025-03-04-11.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:17,717 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BINANCE/btcusdt/2025-03-04-12.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:18,786 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BINANCE/btcusdt/2025-03-04-13.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:20,794 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BINANCE/btcusdt/2025-03-04-14.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:22,605 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BINANCE/btcusdt/2025-03-04-15.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:22,632 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BINANCE/btcusdt/2025-03-04-16.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:22,638 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BINANCE/btcusdt/2025-03-04-17.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:23,372 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BINANCE/btcusdt/2025-03-04-18.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:24,481 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BINANCE/btcusdt/2025-03-04-19.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:25,321 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BINANCE/btcusdt/2025-03-04-20.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:26,239 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BINANCE/btcusdt/2025-03-04-21.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:26,615 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BINANCE/btcusdt/2025-03-04-22.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:26,907 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BINANCE/btcusdt/2025-03-04-23.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:27,487 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BINANCE/btcusdt/2025-03-05-00.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:28,002 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BINANCE/btcusdt/2025-03-05-01.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:28,645 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BINANCE/btcusdt/2025-03-05-02.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:29,180 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BINANCE/btcusdt/2025-03-05-03.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:29,695 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BINANCE/btcusdt/2025-03-05-04.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:30,009 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BINANCE/btcusdt/2025-03-05-05.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:30,308 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BINANCE/btcusdt/2025-03-05-06.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:30,641 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BINANCE/btcusdt/2025-03-05-07.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:31,006 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BINANCE/btcusdt/2025-03-05-08.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:31,631 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BINANCE/btcusdt/2025-03-05-09.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:32,853 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BINANCE/btcusdt/2025-03-05-10.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:33,646 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BINANCE/btcusdt/2025-03-05-11.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:34,677 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BINANCE/btcusdt/2025-03-05-12.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:35,813 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BINANCE/btcusdt/2025-03-05-13.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:37,246 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BINANCE/btcusdt/2025-03-05-14.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:38,686 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BINANCE/btcusdt/2025-03-05-15.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:39,920 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/BINANCE/btcusdt/2025-03-05-16.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:40,024 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/COINBASE/BTC-USD/2025-03-04-00.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:40,204 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/COINBASE/BTC-USD/2025-03-04-01.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:40,346 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/COINBASE/BTC-USD/2025-03-04-02.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:40,405 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/COINBASE/BTC-USD/2025-03-04-03.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:40,461 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/COINBASE/BTC-USD/2025-03-04-04.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:40,513 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/COINBASE/BTC-USD/2025-03-04-05.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:40,557 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/COINBASE/BTC-USD/2025-03-04-06.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:40,602 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/COINBASE/BTC-USD/2025-03-04-07.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:40,652 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/COINBASE/BTC-USD/2025-03-04-08.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:40,688 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/COINBASE/BTC-USD/2025-03-04-09.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:40,722 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/COINBASE/BTC-USD/2025-03-04-10.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:40,761 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/COINBASE/BTC-USD/2025-03-04-11.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:40,823 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/COINBASE/BTC-USD/2025-03-04-12.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:40,923 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/COINBASE/BTC-USD/2025-03-04-13.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:41,094 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/COINBASE/BTC-USD/2025-03-04-14.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:41,248 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/COINBASE/BTC-USD/2025-03-04-15.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:41,400 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/COINBASE/BTC-USD/2025-03-04-16.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:41,525 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/COINBASE/BTC-USD/2025-03-04-17.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:41,637 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/COINBASE/BTC-USD/2025-03-04-18.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:41,761 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/COINBASE/BTC-USD/2025-03-04-19.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:41,874 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/COINBASE/BTC-USD/2025-03-04-20.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:41,963 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/COINBASE/BTC-USD/2025-03-04-21.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:42,007 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/COINBASE/BTC-USD/2025-03-04-22.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:42,056 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/COINBASE/BTC-USD/2025-03-04-23.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:42,119 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/COINBASE/BTC-USD/2025-03-05-00.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:42,172 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/COINBASE/BTC-USD/2025-03-05-01.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:42,240 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/COINBASE/BTC-USD/2025-03-05-02.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:42,293 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/COINBASE/BTC-USD/2025-03-05-03.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:42,347 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/COINBASE/BTC-USD/2025-03-05-04.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:42,378 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/COINBASE/BTC-USD/2025-03-05-05.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:42,406 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/COINBASE/BTC-USD/2025-03-05-06.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:42,440 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/COINBASE/BTC-USD/2025-03-05-07.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:42,471 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/COINBASE/BTC-USD/2025-03-05-08.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:42,512 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/COINBASE/BTC-USD/2025-03-05-09.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:42,579 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/COINBASE/BTC-USD/2025-03-05-10.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:42,624 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/COINBASE/BTC-USD/2025-03-05-11.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:42,697 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/COINBASE/BTC-USD/2025-03-05-12.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:42,784 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/COINBASE/BTC-USD/2025-03-05-13.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:42,903 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/COINBASE/BTC-USD/2025-03-05-14.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:43,026 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/COINBASE/BTC-USD/2025-03-05-15.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:43,127 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/COINBASE/BTC-USD/2025-03-05-16.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:43,143 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/COINBASE/BTC-USDT/2025-03-04-00.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:43,160 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/COINBASE/BTC-USDT/2025-03-04-01.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:43,174 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/COINBASE/BTC-USDT/2025-03-04-02.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:43,179 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/COINBASE/BTC-USDT/2025-03-04-03.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:43,186 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/COINBASE/BTC-USDT/2025-03-04-04.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:43,192 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/COINBASE/BTC-USDT/2025-03-04-05.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:43,197 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/COINBASE/BTC-USDT/2025-03-04-06.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:43,204 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/COINBASE/BTC-USDT/2025-03-04-07.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:43,210 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/COINBASE/BTC-USDT/2025-03-04-08.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:43,215 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/COINBASE/BTC-USDT/2025-03-04-09.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:43,220 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/COINBASE/BTC-USDT/2025-03-04-10.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:43,224 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/COINBASE/BTC-USDT/2025-03-04-11.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:43,228 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/COINBASE/BTC-USDT/2025-03-04-12.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:43,237 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/COINBASE/BTC-USDT/2025-03-04-13.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:43,260 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/COINBASE/BTC-USDT/2025-03-04-14.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:43,278 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/COINBASE/BTC-USDT/2025-03-04-15.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:43,288 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/COINBASE/BTC-USDT/2025-03-04-16.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:43,298 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/COINBASE/BTC-USDT/2025-03-04-17.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:43,307 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/COINBASE/BTC-USDT/2025-03-04-18.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:43,318 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/COINBASE/BTC-USDT/2025-03-04-19.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:43,327 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/COINBASE/BTC-USDT/2025-03-04-20.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:43,336 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/COINBASE/BTC-USDT/2025-03-04-21.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:43,340 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/COINBASE/BTC-USDT/2025-03-04-22.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:43,344 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/COINBASE/BTC-USDT/2025-03-04-23.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:43,355 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/COINBASE/BTC-USDT/2025-03-05-00.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:43,360 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/COINBASE/BTC-USDT/2025-03-05-01.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:43,366 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/COINBASE/BTC-USDT/2025-03-05-02.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:43,372 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/COINBASE/BTC-USDT/2025-03-05-03.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:43,377 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/COINBASE/BTC-USDT/2025-03-05-04.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:43,380 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/COINBASE/BTC-USDT/2025-03-05-05.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:43,384 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/COINBASE/BTC-USDT/2025-03-05-06.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:43,388 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/COINBASE/BTC-USDT/2025-03-05-07.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:43,391 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/COINBASE/BTC-USDT/2025-03-05-08.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:43,396 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/COINBASE/BTC-USDT/2025-03-05-09.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:43,404 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/COINBASE/BTC-USDT/2025-03-05-10.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:43,409 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/COINBASE/BTC-USDT/2025-03-05-11.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:43,415 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/COINBASE/BTC-USDT/2025-03-05-12.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:43,423 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/COINBASE/BTC-USDT/2025-03-05-13.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:43,437 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/COINBASE/BTC-USDT/2025-03-05-14.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:43,451 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/COINBASE/BTC-USDT/2025-03-05-15.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2025-03-05 20:19:43,464 - ERROR - Error processing file /home/astroill/BTC/aggr-server/data/COINBASE/BTC-USDT/2025-03-05-16.gz: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mnt/DATA/@Python/2025/ai-btc/aggr_max_vol_01.py", line 43, in main
    if df.size<len(open(fullname).readlines()):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
